/**
 * Cave à vins
 * API cave à vins
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams }               from '@angular/common/http';

import { Observable }                                        from 'rxjs/Observable';
import '../rxjs-operators';

import { ApiResponse } from '../model/apiResponse';
import { Compartment } from '../model/compartment';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';


@Injectable()
export class CompartmentService {

    protected basePath = 'http://localhost:8080';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (let consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * Create a new add-compartment
     *
     * @param body Compartment object that needs to be added
     */
    public createCompartment(body: Compartment): Observable<{}> {
        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling createCompartment.');
        }

        let currentUser = JSON.parse(localStorage.getItem('currentUser'));

        let headers = this.defaultHeaders;
        headers = headers.set('Authorization', 'Bearer ' + currentUser.token);

        return this.httpClient.post<any>(`${this.basePath}/compartment/create`,
            body,
            {
                headers: headers,
                withCredentials: this.configuration.withCredentials,
            }
        );
    }

    /**
     * Delete a add-compartment
     *
     * @param compartmentId Compartment id to delete
     * @param apiKey
     */
    public deleteCompartment(compartmentId: number, apiKey?: string): Observable<{}> {
        if (compartmentId === null || compartmentId === undefined) {
            throw new Error('Required parameter compartmentId was null or undefined when calling deleteCompartment.');
        }

        let headers = this.defaultHeaders;
        if (apiKey !== undefined && apiKey !== null) {
            headers = headers.set('api_key', String(apiKey));
        }

        // authentication (vinecellar_auth) required
        if (this.configuration.accessToken) {
            let accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        let httpHeaderAcceptSelected: string = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.delete<any>(`${this.basePath}/compartment/delete/${encodeURIComponent(String(compartmentId))}`,
            {
                headers: headers,
                withCredentials: this.configuration.withCredentials,
            }
        );
    }

    /**
     * Update an existing add-compartment
     *
     * @param formData data
     */
    public updateCompartment(formData: FormData): Observable<{}> {
        let currentUser = JSON.parse(localStorage.getItem('currentUser'));

        let headers = this.defaultHeaders;
        headers = headers.set('Authorization', 'Bearer ' + currentUser.token);

            return this.httpClient.post<any>(`${this.basePath}/compartment/update`,
              formData,
                {
                    headers: headers,
                    withCredentials: this.configuration.withCredentials,
                }
            );
    }

    /**
     * Upload an image for the add-compartment
     *
     * @param formData data to pass to server
     */
    public uploadCompartmentFile(formData: FormData): Observable<ApiResponse> {
        let currentUser = JSON.parse(localStorage.getItem('currentUser'));

        let headers = this.defaultHeaders;
        headers = headers.set('Authorization', 'Bearer ' + currentUser.token);

        return this.httpClient.post<any>(`${this.basePath}/images/upload`,
            formData,
            {
                headers: headers,
                withCredentials: this.configuration.withCredentials,
            }
        );
    }

}
