/**
 * Cave à vins
 * API cave à vins
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders }                           from '@angular/common/http';

import { Observable }                                        from 'rxjs/Observable';
import '../rxjs-operators';


import { BASE_PATH }                                         from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class OauthService {

  protected basePath = 'http://localhost:8080';
  public configuration = new Configuration();

  isLogged: boolean;

  constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
    if (basePath) {
      this.basePath = basePath;
    }
    if (configuration) {
      this.configuration = configuration;
      this.basePath = basePath || configuration.basePath || this.basePath;
    }

    this.isLogged = false;
  }

  /**
   * Give token for the user
   *
   * @param login
   * @param password
   * @param grant_type
   */
  public getToken(login: string, password: string, grant_type: string): Observable<any> {
    let params = new URLSearchParams();
    params.append('username', login);
    params.append('password', password);
    params.append('grant_type','password');

    let headers = new HttpHeaders({'Content-type': 'application/x-www-form-urlencoded; charset=utf-8', 'Authorization': 'Basic '+btoa("gigy:secret")});
    let options = { headers: headers };

    return this.httpClient.post<any>(`${this.basePath}/oauth/token`, params.toString(), options);
  }

  public isLoggedIn() {
    let currentUser = JSON.parse(localStorage.getItem('currentUser'));

    if(currentUser)
      return true;
    else
      return false;
  }

  public isAdmin() {
    let currentUser = JSON.parse(localStorage.getItem('currentUser'));

    return currentUser && currentUser.user.roles[0].name == 'ADMIN_ROLE';
  }

  public isSimpleUser() {
    let currentUser = JSON.parse(localStorage.getItem('currentUser'));

    return currentUser && currentUser.user.roles[0].name == 'USER_ROLE';
  }
}
