/**
 * Cave à vins
 * API cave à vins
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams }               from '@angular/common/http';

import { Observable }                                        from 'rxjs/Observable';
import '../rxjs-operators';

import { User } from '../model/user';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';
import {Bottle} from '../model/bottle';


@Injectable()
export class OauthService {

  protected basePath = 'http://localhost:8080';
  public defaultHeaders = new HttpHeaders();
  public configuration = new Configuration();

  constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
    if (basePath) {
      this.basePath = basePath;
    }
    if (configuration) {
      this.configuration = configuration;
      this.basePath = basePath || configuration.basePath || this.basePath;
    }
  }

  /**
   * Give token for the user
   *
   * @param login
   * @param password
   * @param grant_type
   */
  public getToken(login: string, password: string, grant_type: string): Observable<any> {
    let headers = this.defaultHeaders;

    headers.set('Authorization', 'Basic Z2lneTpzZWNyZXQ=');
    headers.set('Content-type', 'application/x-www-form-urlencoded');

    return this.httpClient.get<any>(`${this.basePath}/oauth/token?username=${encodeURIComponent(String(login))}&password=${encodeURIComponent(String(password))}&grant_type=${encodeURIComponent(String(grant_type))}`,
      {
        headers: headers,
        withCredentials: this.configuration.withCredentials,
      }
    );
  }
}
