/**
 * Cave à vins
 * API cave à vins
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { BottleType } from './bottleType';
import { Compartment } from './compartment';
import { User } from './user';


export interface Bottle {
    id?: number;
    photoUrl?: string;
    owner?: User;
    type?: BottleType;
    compartment?: Compartment;
    nbBottles?: number;
}
